CREATE TABLE Properties (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR (30),
    ADDRESS VARCHAR (100),
    CITY VARCHAR (100),
    STATE VARCHAR (2),
    ZIP INTEGER,
    IMG TEXT,
    MORTGAGE DECIMAL,
    RENT DECIMAL
);